version: "3.8"

services:
  api:
    build: "api-image"
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
