version: "3.3"

services:
  api:
    build: "api-image"
    command: gunicorn -w 2 --bind 0.0.0.0:5000 myapp.app:app
    expose:
      - 5000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/certs-data/:/data/letsencrypt/
    depends_on:
      - api
